language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: ${organizationName}
    token:
      secure: ${token}
jdk:
  - oraclejdk8
script:
  - gradle clean org.jacoco:jacoco-maven-plugin:prepare-agent build sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
