app:
  build: ./tomcatSetup/
  container_name: yam_tomcat
  ports:
    - "8888:8888"
  links:
    - db
db:
  build: ./dbSetup/
  container_name: yam_mysql
  ports:
    - "3333:3333"
  environment:
    MYSQL_REMOTE_HOST: db
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
